# Generated by Django 6.0.3 on 2026-03-17 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('school', 'School Programme'), ('plus_two', '+2 Programme')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('session', models.CharField(max_length=20)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('subject_or_stream', models.CharField(blank=True, max_length=120)),
                ('grade_info', models.CharField(blank=True, max_length=120)),
                ('availability', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='App.admission')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
