# Generated by Django 4.2.16 on 2026-03-17 19:21

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_gallery_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/attachments/', validators=[App.models.validate_file])),
                ('converted_pdf', models.FileField(blank=True, null=True, upload_to='notices/pdfs/')),
            ],
        ),
    ]
